# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: set-version
    name: Set version in Version.elm
    entry: pre_commit_hooks/set_version.sh
    language: script
    always_run: true
