version: "3.1"

services:

  graphsense-dashboard:
    image: graphsense-dashboard
    container_name: graphsense-dashboard
    hostname: graphsense-dashboard
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${DASHBOARD_PORT}:8000
    environment:
      REST_URL: "${REST_URL}"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
