version: "3.1"

services:

  graphsense-dashboard:
    image: ${DOCKER_IMAGE_NAME:-graphsense-dashboard}
    container_name: ${DOCKER_CONTAINER_NAME:-graphsense-dashboard}
    hostname: ${DOCKER_HOSTNAME:-graphsense-dashboard}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${DASHBOARD_PORT}:8000
    environment:
      REST_URL: "${REST_URL}"
    command: ["nginx", "-g", "daemon off;"]
    restart: always
