name: Build the dashboard

on: 
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: cp config/Config.elm.tmp config/Config.elm
      - run: cp env.template .env
      - run: npm run build --if-present
